package GUI;

import Entities.Usuario;
import Services.UsuarioService;
import java.awt.Color;
import javax.swing.table.DefaultTableModel;

public class Home extends javax.swing.JFrame {

    DefaultTableModel dtmUsuario;
    
    public Home() {
        initComponents();
        // CARGAR tablas cuando estén inicializadas.
        dtmUsuario = (DefaultTableModel) tblUsuarios.getModel();
        initData();
    }
    
    private void initData(){
        recargarTabla();
    }
    
    private void recargarTabla(){
        dtmUsuario.setRowCount(0);
        
        UsuarioService userS = new UsuarioService();
        for(Usuario usuario : userS.listar()){
            String[] userArray = {
                String.valueOf(usuario.getIdUsuario()),
                usuario.getNombre(),
                usuario.getApellido(),
                usuario.getDni()
            };
            dtmUsuario.addRow(userArray);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popOpciones = new javax.swing.JPopupMenu();
        miRegistrarEntrada = new javax.swing.JMenuItem();
        lblBuscar = new javax.swing.JLabel();
        tfdBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        scrollUsuarios = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        lblCoincidencias = new javax.swing.JLabel();

        miRegistrarEntrada.setText("Registrar Entrada");
        miRegistrarEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRegistrarEntradaActionPerformed(evt);
            }
        });
        popOpciones.add(miRegistrarEntrada);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblBuscar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblBuscar.setText("BUSCAR A USUARIO PARA EL REGISTRO DE ASISTENCIA");

        tfdBuscar.setForeground(java.awt.Color.gray);
        tfdBuscar.setText("Ingrese nombre de usuario...");
        tfdBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tfdBuscar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfdBuscarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfdBuscarFocusLost(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "COD", "Nombre", "Apellido", "DNI"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblUsuarios.setComponentPopupMenu(popOpciones);
        tblUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblUsuarios.setShowGrid(true);
        tblUsuarios.setShowHorizontalLines(true);
        scrollUsuarios.setViewportView(tblUsuarios);
        tblUsuarios.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tblUsuarios.getColumnModel().getColumnCount() > 0) {
            tblUsuarios.getColumnModel().getColumn(0).setMinWidth(50);
            tblUsuarios.getColumnModel().getColumn(0).setMaxWidth(100);
        }

        lblCoincidencias.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCoincidencias.setText("Coincidencias de Búsqueda");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCoincidencias)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblBuscar)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(tfdBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnBuscar))
                        .addComponent(scrollUsuarios)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblBuscar)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfdBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(3, 3, 3)))
                .addComponent(lblCoincidencias)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scrollUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfdBuscarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfdBuscarFocusGained
        if ("Ingrese nombre de usuario...".equals(tfdBuscar.getText())){
            tfdBuscar.setText("");
            tfdBuscar.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_tfdBuscarFocusGained

    private void tfdBuscarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfdBuscarFocusLost
        if (tfdBuscar.getText().length() == 0){
            tfdBuscar.setText("Ingrese nombre de usuario...");
            tfdBuscar.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_tfdBuscarFocusLost

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        //TODO: Añadir función de búsqueda.
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void miRegistrarEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRegistrarEntradaActionPerformed
        if (tblUsuarios.getSelectedRow() != -1){
            // OBTENER ID del Usuario.
            int idRow = tblUsuarios.getSelectedRow();
            int idUsuario = Integer.parseInt(dtmUsuario.getValueAt(idRow, 0).toString());
            // COMPROBAR que el ID tenga posible asistencia para hoy.
            UsuarioService userS = new UsuarioService();
            if (userS.getEntrada(idUsuario) == null) return;
            // ABRIR el Dialog correspondiente.
            DRegistroAsistencia registrarEntrada = new DRegistroAsistencia(this, true, idUsuario);
            registrarEntrada.setLocationRelativeTo(this);
            registrarEntrada.setVisible(true);
        } else {
            DialogAlert.genericDialog("No hay filas seleccionadas.", "SIN FILAS SELECCIONADAS", 2);
        }
    }//GEN-LAST:event_miRegistrarEntradaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblCoincidencias;
    private javax.swing.JMenuItem miRegistrarEntrada;
    private javax.swing.JPopupMenu popOpciones;
    private javax.swing.JScrollPane scrollUsuarios;
    private javax.swing.JTable tblUsuarios;
    private javax.swing.JTextField tfdBuscar;
    // End of variables declaration//GEN-END:variables
}
